/*
 * Generated by util/mkerr.pl DO NOT EDIT
 * Copyright 1995-2018 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the OpenSSL license (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#include <stdio.h>
#include <openssl/err.h>
#include <openssl/smx.h>

/* BEGIN ERROR CODES */
#ifndef OPENSSL_NO_ERR

# define ERR_FUNC(func) ERR_PACK(ERR_LIB_SM9,func,0)
# define ERR_REASON(reason) ERR_PACK(ERR_LIB_SM9,0,reason)

static ERR_STRING_DATA SMX_str_functs[] = {
    {ERR_FUNC(SMX_F_DO_SMX_KEY_PRINT), "do_smx_key_print"},
    {ERR_FUNC(SMX_F_DO_SMX_MASTER_KEY_PRINT), "do_smx_master_key_print"},
    {ERR_FUNC(SMX_F_PKEY_SMX_COPY), "pkey_smx_copy"},
    {ERR_FUNC(SMX_F_PKEY_SMX_CTRL), "pkey_smx_ctrl"},
    {ERR_FUNC(SMX_F_PKEY_SMX_CTRL_STR), "pkey_smx_ctrl_str"},
    {ERR_FUNC(SMX_F_PKEY_SMX_DECRYPT), "pkey_smx_decrypt"},
    {ERR_FUNC(SMX_F_PKEY_SMX_INIT), "pkey_smx_init"},
    {ERR_FUNC(SMX_F_PKEY_SMX_MASTER_COPY), "pkey_smx_master_copy"},
    {ERR_FUNC(SMX_F_PKEY_SMX_MASTER_CTRL), "pkey_smx_master_ctrl"},
    {ERR_FUNC(SMX_F_PKEY_SMX_MASTER_CTRL_STR), "pkey_smx_master_ctrl_str"},
    {ERR_FUNC(SMX_F_PKEY_SMX_MASTER_ENCRYPT), "pkey_smx_master_encrypt"},
    {ERR_FUNC(SMX_F_PKEY_SMX_MASTER_INIT), "pkey_smx_master_init"},
    {ERR_FUNC(SMX_F_PKEY_SMX_MASTER_KEYGEN), "pkey_smx_master_keygen"},
    {ERR_FUNC(SMX_F_PKEY_SMX_MASTER_VERIFY), "pkey_smx_master_verify"},
    {ERR_FUNC(SMX_F_PKEY_SMX_SIGN), "pkey_smx_sign"},
    {ERR_FUNC(SMX_F_SMX_CIPHERTEXT_SIZE), "SMX_ciphertext_size"},
    {ERR_FUNC(SMX_F_SMX_COMPUTE_SHARE_KEY_A), "SMX_compute_share_key_A"},
    {ERR_FUNC(SMX_F_SMX_COMPUTE_SHARE_KEY_B), "SMX_compute_share_key_B"},
    {ERR_FUNC(SMX_F_SMX_DECRYPT), "SMX_decrypt"},
    {ERR_FUNC(SMX_F_SMX_ENCRYPT), "SMX_encrypt"},
    {ERR_FUNC(SMX_F_SMX_EXTRACT_PUBLIC_PARAMETERS),
     "SMX_extract_public_parameters"},
    {ERR_FUNC(SMX_F_SMX_GENERATE_KEY_EXCHANGE), "SMX_generate_key_exchange"},
    {ERR_FUNC(SMX_F_SMX_GENERATE_MASTER_SECRET),
     "SMX_generate_master_secret"},
    {ERR_FUNC(SMX_F_SMX_KEY_NEW), "SMX_KEY_new"},
    {ERR_FUNC(SMX_F_SMX_MASTER_KEY_EXTRACT_KEY),
     "SMX_MASTER_KEY_extract_key"},
    {ERR_FUNC(SMX_F_SMX_MASTER_KEY_NEW), "SMX_MASTER_KEY_new"},
    {ERR_FUNC(SMX_F_SMX_MASTER_OLD_PRIV_DECODE),
     "smx_master_old_priv_decode"},
    {ERR_FUNC(SMX_F_SMX_MASTER_PRIV_DECODE), "smx_master_priv_decode"},
    {ERR_FUNC(SMX_F_SMX_MASTER_PRIV_ENCODE), "smx_master_priv_encode"},
    {ERR_FUNC(SMX_F_SMX_MASTER_PUB_DECODE), "smx_master_pub_decode"},
    {ERR_FUNC(SMX_F_SMX_OLD_PRIV_DECODE), "smx_old_priv_decode"},
    {ERR_FUNC(SMX_F_SMX_PRIV_DECODE), "smx_priv_decode"},
    {ERR_FUNC(SMX_F_SMX_PRIV_ENCODE), "smx_priv_encode"},
    {ERR_FUNC(SMX_F_SMX_PUB_DECODE), "smx_pub_decode"},
    {ERR_FUNC(SMX_F_SMX_SIGN), "SMX_sign"},
    {ERR_FUNC(SMX_F_SMX_SIGNFINAL), "SMX_SignFinal"},
    {ERR_FUNC(SMX_F_SMX_SIGNINIT), "SMX_SignInit"},
    {ERR_FUNC(SMX_F_SMX_UNWRAP_KEY), "SMX_unwrap_key"},
    {ERR_FUNC(SMX_F_SMX_VERIFY), "SMX_verify"},
    {ERR_FUNC(SMX_F_SMX_VERIFYFINAL), "SMX_VerifyFinal"},
    {ERR_FUNC(SMX_F_SMX_VERIFYINIT), "SMX_VerifyInit"},
    {ERR_FUNC(SMX_F_SMX_WRAP_KEY), "SMX_wrap_key"},
    {0, NULL}
};

static ERR_STRING_DATA SMX_str_reasons[] = {
    {ERR_REASON(SMX_R_BUFFER_TOO_SMALL), "buffer too small"},
    {ERR_REASON(SMX_R_DECODE_ERROR), "decode error"},
    {ERR_REASON(SMX_R_DIGEST_FAILURE), "digest failure"},
    {ERR_REASON(SMX_R_EC_LIB), "ec lib"},
    {ERR_REASON(SMX_R_EXTENSION_FIELD_ERROR), "extension field error"},
    {ERR_REASON(SMX_R_IDENTITY_REQUIRED), "identity required"},
    {ERR_REASON(SMX_R_INVALID_DIGEST_TYPE), "invalid digest type"},
    {ERR_REASON(SMX_R_INVALID_ENCRYPT_SCHEME), "invalid encrypt scheme"},
    {ERR_REASON(SMX_R_INVALID_HASH1), "invalid hash1"},
    {ERR_REASON(SMX_R_INVALID_HASH2_DIGEST), "invalid hash2 digest"},
    {ERR_REASON(SMX_R_INVALID_ID), "invalid id"},
    {ERR_REASON(SMX_R_INVALID_KEM_KEY_LENGTH), "invalid kem key length"},
    {ERR_REASON(SMX_R_INVALID_KEY_AGREEMENT_CHECKSUM),
     "invalid key agreement checksum"},
    {ERR_REASON(SMX_R_INVALID_KEY_USAGE), "invalid key usage"},
    {ERR_REASON(SMX_R_INVALID_PAIRING), "invalid pairing"},
    {ERR_REASON(SMX_R_INVALID_PAIRING_TYPE), "invalid pairing type"},
    {ERR_REASON(SMX_R_INVALID_POINTPPUB), "invalid pointppub"},
    {ERR_REASON(SMX_R_INVALID_PRIVATE_POINT), "invalid private point"},
    {ERR_REASON(SMX_R_INVALID_SCHEME), "invalid scheme"},
    {ERR_REASON(SMX_R_INVALID_SIGNATURE), "invalid signature"},
    {ERR_REASON(SMX_R_INVALID_SIGNATURE_FORMAT), "invalid signature format"},
    {ERR_REASON(SMX_R_INVALID_SIGN_MD), "invalid sign md"},
    {ERR_REASON(SMX_R_INVALID_SIGN_SCHEME), "invalid sign scheme"},
    {ERR_REASON(SMX_R_INVALID_SMX_SCHEME), "invalid smx scheme"},
    {ERR_REASON(SMX_R_NO_MASTER_SECRET), "no master secret"},
    {ERR_REASON(SMX_R_PAIRING_ERROR), "pairing error"},
    {ERR_REASON(SMX_R_PLAINTEXT_TOO_LONG), "plaintext too long"},
    {ERR_REASON(SMX_R_RATE_PAIRING_ERROR), "rate pairing error"},
    {ERR_REASON(SMX_R_SIGNER_ID_REQUIRED), "signer id required"},
    {ERR_REASON(SMX_R_TWIST_CURVE_ERROR), "twist curve error"},
    {ERR_REASON(SMX_R_VERIFY_FAILURE), "verify failure"},
    {ERR_REASON(SMX_R_ZERO_ID), "zero id"},
    {0, NULL}
};

#endif

int ERR_load_SMX_strings(void)
{
#ifndef OPENSSL_NO_ERR

    if (ERR_func_error_string(SMX_str_functs[0].error) == NULL) {
        ERR_load_strings(0, SMX_str_functs);
        ERR_load_strings(0, SMX_str_reasons);
    }
#endif
    return 1;
}
